# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ProfessorLaw's Basement - Dev Blog
email: cyril.canonico@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  28 years old. Lead Developer @ MaPS System
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://professorlaw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Profess0rLaw
github_username:  ProfessorLaw
permalink: pretty
logo: "https://gravatar.com/userimage/28964835/1ec6c3b531cab26a24a6b3f7fdc77f87.jpg?size=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_image: "/blog/background.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# Build settings
markdown: kramdown
remote_theme:  daviddarnes/alembic@main
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
